output "vpc_id" {
  value = module.vpc.vpc_id
}

output "vpc_all_subnets" {
  description = "Kubernetes VPC All Subnets"
  value       = data.aws_subnet_ids.eks_subnets.ids
}

output "vpc_public_subnets" {
  description = "Kubernetes VPC Public Subnets"
  value       = data.aws_subnet_ids.eks_subnets_public.ids
}

output "vpc_private_subnets" {
  description = "Kubernetes VPC Private Subnets"
  value       = data.aws_subnet_ids.eks_subnets_private.ids
}


output "aws_efs_id" {
  description = "AWS EFS ID to be use in EKS Persistence Volume"
  value       = aws_efs_file_system.aws_efs.id
}


output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = local.cluster_name
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

/*
output "eks_node_groups_node_groups" {
  value = module.eks_node_groups.node_groups
}

output "eks_node_groups_aws_auth_roles" {
  value = module.eks_node_groups.aws_auth_roles
}
*/

